configuration: Release

# scripts to run before build
before_build:
  - dotnet restore
  - nuget restore
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
build_script:
  - dotnet build .\UnitOfWork.Unity.Inteception.sln
  - dotnet pack UnitOfWork.Unity.Inteception
  
test:
  # only assemblies to test
  assemblies:
    only:
      - '**\*.Tests.dll'
  
artifacts:
  - path: UnitOfWork.Unity.Inteception\bin\Release
    name: UnitOfWork.Unity.Inteception_bin
    
  - path: '**\UnitOfWork.Unity.Inteception\bin\Release\*.nupkg'
