before_build:
  - nuget restore
test:
  assemblies:
    only:
      - Bitmex.NET.UnitTests.dll
after_build:
  - nuget pack %APPVEYOR_BUILD_FOLDER%\UnitOfWork.Unity.Inteception\UnitOfWork.Unity.Inteception.csproj -Properties Configuration=Release -Build -OutputDirectory %APPVEYOR_BUILD_FOLDER%\UnitOfWork.Unity.Inteception\bin

artifacts:
  - path: UnitOfWork.Unity.Inteception\bin\Release
    name: UnitOfWork.Unity.Inteception_bin
    
  - path: UnitOfWork.Unity.Inteception\bin\*.nupkg