configuration: Release

# scripts to run before build
before_build:
  - dotnet restore

build_script:
  - dotnet build .\UnitOfWork.Unity.Inteception.sln

test_script:
  - dotnet test .\UnitOfWork.Unity.Inteception.Tests\
  
artifacts:
  - path: UnitOfWork.Unity.Inteception\bin\Release
    name: UnitOfWork.Unity.Inteception_bin
    
  - path: UnitOfWork.Unity.Inteception\bin\*.nupkg
