configuration: Release

# scripts to run before build
before_build:
  - dotnet restore

build_script:
  - dotnet build .\Bitmex.NET.UnitTests.sln

test_script:
  - dotnet test .\Bitmex.NET.UnitTests.Tests\